export default {
    GET_TRENDSANDROID_PENDING: "GET_TRENDSANDROID_PENDING",
    GET_TRENDSANDROID_FULFILLED: "GET_TRENDSANDROID_FULFILLED",
    GET_TRENDSANDROID_REJECT: "GET_TRENDSANDROID_REJECT",

    GET_TRENDSIOS_PENDING: "GET_TRENDSIOS_PENDING",
    GET_TRENDSIOS_FULFILLED: "GET_TRENDSIOS_FULFILLED",
    GET_TRENDSIOS_REJECT: "GET_TRENDSIOS_REJECT",

    GET_TRENDSANDROIDTOP_PENDING: "GET_TRENDSANDROIDTOP_PENDING",
    GET_TRENDSANDROIDTOP_FULFILLED: "GET_TRENDSANDROIDTOP_FULFILLED",
    GET_TRENDSANDROIDTOP_REJECT: "GET_TRENDSANDROIDTOP_REJECT",

    GET_ANDROIDVERSION_PENDING: "GET_ANDROIDVERSION_PENDING",
    GET_ANDROIDVERSION_FULFILLED: "GET_ANDROIDVERSION_FULFILLED",
    GET_ANDROIDVERSION_REJECT: "GET_ANDROIDVERSION_REJECT",

    GET_ANDROID_CRASH_SUMMARY_BY_VERSION_PENDING: "GET_ANDROID_CRASH_SUMMARY_BY_VERSION_PENDING",
    GET_ANDROID_CRASH_SUMMARY_BY_VERSION_FULFILLED: "GET_ANDROID_CRASH_SUMMARY_BY_VERSION_FULFILLED",
    GET_ANDROID_CRASH_SUMMARY_BY_VERSION_REJECT: "GET_ANDROID_CRASH_SUMMARY_BY_VERSION_REJECT",

    GET_MICROAPPS_PENDING: "GET_MICROAPPS_PENDING",
    GET_MICROAPPS_FULFILLED: "GET_MICROAPPS_FULFILLED",
    GET_MICROAPPS_REJECT: "GET_MICROAPPS_REJECT",
};
