export default {

    GET_MQTTRESULT_PENDING: "GET_MQTTRESULT_PENDING",
    GET_MQTTRESULT_FULFILLED: "GET_SHADOWTOWERSUITES_FULFILLED",
    GET_MQTTRESULT_REJECT: "GET_MQTTRESULT_REJECT",

    GET_MQTTRESP_PENDING: "GET_MQTTRESP_PENDING",
    GET_MQTTRESP_FULFILLED: "GET_MQTTRESP_FULFILLED",
    GET_MQTTRESP_REJECT: "GET_MQTTRESP_REJECT",

    GET_MQTTRESP24H_PENDING: "GET_MQTTRESP24H_PENDING",
    GET_MQTTRESP24H_FULFILLED: "GET_MQTTRESP24H_FULFILLED",
    GET_MQTTRESP24H_REJECT: "GET_MQTTRESP24H_REJECT",

    GET_CARDDATA_PENDING: "GET_CARDDATA_PENDING",
    GET_CARDDATA_FULFILLED: "GET_CARDDATA_FULFILLED",
    GET_CARDDATA_REJECT: "GET_CARDDATA_REJECT",
};
