export default {

    GET_SHADOWTOWERSUITES_PENDING: "GET_SHADOWTOWERSUITES_PENDING",
    GET_SHADOWTOWERSUITES_FULFILLED: "GET_SHADOWTOWERSUITES_FULFILLED",
    GET_SHADOWTOWERSUITES_REJECT: "GET_SHADOWTOWERSUITES_REJECT",


    GET_SHADOWTOWERRUNS_PENDING: "GET_SHADOWTOWERRUNS_PENDING",
    GET_SHADOWTOWERRUNS_FULFILLED: "GET_SHADOWTOWERRUNS_FULFILLED",
    GET_SHADOWTOWERRUNS_REJECT: "GET_SHADOWTOWERRUNS_REJECT",

    GET_SHADOWTOWERTESTS_PENDING:   "GET_SHADOWTOWERTESTS_PENDING",
    GET_SHADOWTOWERTESTS_FULFILLED: "GET_SHADOWTOWERTESTS_FULFILLED",
    GET_SHADOWTOWERTESTS_REJECT:    "GET_SHADOWTOWERTESTS_REJECT",

};
