export default {

    GET_NAMESPACE_PENDING: "GET_NAMESPACE_PENDING",
    GET_NAMESPACE_FULFILLED: "GET_NAMESPACE_FULFILLED",
    GET_NAMESPACE_REJECT: "GET_NAMESPACE_REJECT",

    GET_COMPONENT_PENDING: "GET_COMPONENT_PENDING",
    GET_COMPONENT_FULFILLED: "GET_COMPONENT_FULFILLED",
    GET_COMPONENT_REJECT: "GET_COMPONENT_REJECT",

    GET_SUITES_PENDING: "GET_SUITES_PENDING",
    GET_SUITES_FULFILLED: "GET_SUITES_FULFILLED",
    GET_SUITES_REJECT: "GET_SUITES_REJECT",

    CREATE_COMPONENT_PENDING: "CREATE_COMPONENT_PENDING",
    CREATE_COMPONENT_FULFILLED: "CREATE_COMPONENT_FULFILLED",
    CREATE_COMPONENT_REJECT: "CREATE_COMPONENT_REJECT",

    CREATE_SUITE_PENDING: "CREATE_SUITE_PENDING",
    CREATE_SUITE_FULFILLED: "CREATE_SUITE_FULFILLED",
    CREATE_SUITE_REJECT: "CREATE_SUITE_REJECT",

    UPDATE_SUITE_PENDING: "UPDATE_SUITE_PENDING",
    UPDATE_SUITE_FULFILLED: "UPDATE_SUITE_FULFILLED",
    UPDATE_SUITE_REJECT: "UPDATE_SUITE_REJECT",

    DELETE_SUITE_PENDING: "DELETE_SUITE_PENDING",
    DELETE_SUITE_FULFILLED: "DELETE_SUITE_FULFILLED",
    DELETE_SUITE_REJECT: "DELETE_SUITE_REJECT"

};
