export default {

    GET_SUITE_PENDING: "GET_SUITE_PENDING",
    GET_SUITE_FULFILLED: "GET_SUITE_FULFILLED",
    GET_SUITE_REJECT: "GET_SUITE_REJECT",

    CHECK_EXECUTING_FULFILLED: "CHECK_EXECUTING_FULFILLED",
    STARTING_TEST_FULFILLED: "STARTING_TEST_FULFILLED",

    STOP_TEST_PENDING: "STOP_TEST_PENDING",
    STOP_TEST_FULFILLED: "STOP_TEST_FULFILLED",
    STOP_TEST_REJECT: "STOP_TEST_REJECT",

    RUNNINGTEST_SUMMARY_PENDING: "RUNNINGTEST_SUMMARY_PENDING",
    RUNNINGTEST_SUMMARY_FULFILLED: "RUNNINGTEST_SUMMARY_FULFILLED",
    RUNNINGTEST_SUMMARY_REJECT: "RUNNINGTEST_SUMMARY_REJECT",
};
