export default {

    GET_RUN_RESULTS_PENDING: "GET_RUN_RESULTS_PENDING",
    GET_RUN_RESULTS_FULFILLED: "GET_RUN_RESULTS_FULFILLED",
    GET_RUN_RESULTS_REJECT: "GET_RUN_RESULTS_REJECT",

    GET_RUN_DETAILS_PENDING: "GET_RUN_DETAILS_PENDING",
    GET_RUN_DETAILS_FULFILLED: "GET_RUN_DETAILS_FULFILLED",
    GET_RUN_DETAILS_REJECT: "GET_RUN_DETAILS_REJECT",

};
