export default {

    GET_SUMMARY_PENDING: "GET_SUMMARY_PENDING",
    GET_SUMMARY_FULFILLED: "GET_SUMMARY_FULFILLED",
    GET_SUMMARY_REJECT: "GET_SUMMARY_REJECT",


    GET_RUNHISTORY_PENDING: "GET_RUNHISTORY_PENDING",
    GET_RUNHISTORY_FULFILLED: "GET_RUNHISTORY_FULFILLED",
    GET_RUNHISTORY_REJECT: "GET_RUNHISTORY_REJECT",

    GET_STATS_PENDING:   "GET_STATS_PENDING",
    GET_STATS_FULFILLED: "GET_STATS_FULFILLED",
    GET_STATS_REJECT:    "GET_STATS_REJECT",


    GET_RUNS_PENDING:   "GET_RUNS_PENDING",
    GET_RUNS_FULFILLED: "GET_RUNS_FULFILLED",
    GET_RUNS_REJECT:    "GET_RUNS_REJECT",
};
