export default {

    GET_DROGON_RUNNING_SUMMARY_PENDING: "GET_DROGON_RUNNING_SUMMARY_PENDING",
    GET_DROGON_RUNNING_SUMMARY_FULFILLED: "GET_DROGON_RUNNING_SUMMARY_FULFILLED",
    GET_DROGON_RUNNING_SUMMARY_REJECT: "GET_DROGON_RUNNING_SUMMARY_REJECT",



    GET_DROGON_RUNNING_DETAILS_PENDING: "GET_DROGON_RUNNING_DETAILS_PENDING",
    GET_DROGON_RUNNING_DETAILS_FULFILLED: "GET_DROGON_RUNNING_DETAILS_FULFILLED",
    GET_DROGON_RUNNING_DETAILS_REJECT: "GET_DROGON_RUNNING_DETAILS_REJECT",

};
