export default {


    GET_COMPONENT_PENDING: "GET_DROGON_COMPONENT_PENDING",
    GET_COMPONENT_FULFILLED: "GET_DROGON_COMPONENT_FULFILLED",
    GET_COMPONENT_REJECT: "GET_DROGON_COMPONENT_REJECT",

    GET_SUITE_PENDING: "GET_DROGON_SUITE_PENDING",
    GET_SUITE_FULFILLED: "GET_DROGON_SUITE_FULFILLED",
    GET_SUITE_REJECT: "GET_DROGON_SUITE_REJECT",

    GET_SUITE_DETAILS_PENDING: "GET_DROGON_SUITE_DETAILS_PENDING",
    GET_SUITE_DETAILS_FULFILLED: "GET_DROGON_SUITE_DETAILS_FULFILLED",
    GET_SUITE_DETAILS_REJECT: "GET_DROGON_SUITE_DETAILS_REJECT",

    GET_DROGON_HARDWARE_AVAILABILITY_PENDING: "GET_DROGON_HARDWARE_AVAILABILITY_PENDING",
    GET_DROGON_HARDWARE_AVAILABILITY_FULFILLED: "GET_DROGON_HARDWARE_AVAILABILITY_FULFILLED",
    GET_DROGON_HARDWARE_AVAILABILITY_REJECT: "GET_DROGON_HARDWARE_AVAILABILITY_REJECT",

    GET_DROGON_START_INSTANCES_PENDING: "GET_DROGON_START_INSTANCES_PENDING",
    GET_DROGON_START_INSTANCES_FULFILLED: "GET_DROGON_START_INSTANCES_FULFILLED",
    GET_DROGON_START_INSTANCES_REJECT: "GET_DROGON_START_INSTANCES_REJECT",

    GET_DROGON_PROVISIONING_PENDING: "GET_DROGON_PROVISIONING_PENDING",
    GET_DROGON_PROVISIONING_FULFILLED: "GET_DROGON_PROVISIONING_FULFILLED",
    GET_DROGON_PROVISIONING_REJECT: "GET_DROGON_PROVISIONING_REJECT",

    GET_DROGON_TEST_STARTED_PENDING: "GET_DROGON_TEST_STARTED_PENDING",
    GET_DROGON_TEST_STARTED_FULFILLED: "GET_DROGON_TEST_STARTED_FULFILLED",
    GET_DROGON_TEST_STARTED_REJECT: "GET_DROGON_TEST_STARTED_REJECT",

    STOP_DROGON_TEST_PENDING: "STOP_DROGON_TEST_PENDING",
    STOP_DROGON_TEST_FULFILLED: "STOP_DROGON_TEST_FULFILLED",
    STOP_DROGON_TEST_REJECT: "STOP_DROGON_TEST_REJECT",

};
